
package com.news.egg.enumeraciones;

public enum ObraSocial {
    Ninguna,
    MUTUAL_DEL_PERSONAL_DEL_AGUA_Y_LA_ENERGIA_DE_MENDOZA,
    OBRA_SOCIAL_FERROVIARIA,
    OBRA_SOCIAL_YACIMIENTOS_CARBONIFEROS,
    OBRA_SOCIAL_DE_LA_PREVENCION_Y_LA_SALUD,
    OBRA_SOCIAL_DE_CHOFERES_DE_CAMIONES;   
}
